# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/msm8994-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter libra leo,$(TARGET_DEVICE)),)

endif
